vetWeb/soin/soin/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_views
from portals import views as portal_views

from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth.decorators import login_required

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('vet.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls, name='admin-vet'),
    #users sign up
    path('user/signup/vet_officer/', user_views.vet0fficer_signup_view, name='vet-register'),
    path('user/signup/farmer/',user_views.farmer_signup_view,name='farmer-register'),
    path('user/signup/student/',user_views.student_signup_view,name='student-register'),
    #users login 
    path('vet/login/',user_views.vet_login,name='vet-login'),
    path('farmer/login/',user_views.farmer_login,name='farmer-login'),
    path('student/login/',user_views.student_login,name='student-login'),
    path('logout/', user_views.user_logout, name='logout'),
    #password reset
    path("password-reset", auth_views.PasswordResetView.as_view(template_name="user/password_reset.html"), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(template_name="user/password_reset_done.html"), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>", auth_views.PasswordResetConfirmView.as_view( template_name="user/password_reset_confirm.html"), name="password_reset_confirm"),
    path("password-reset-complete/", auth_views.PasswordResetCompleteView.as_view(template_name="user/password_reset_complete.html"), name="password_reset_complete"),

    #users portals
    path('vet_portal/', portal_views.portal_vet, name='vet-portal'),
    path('farmer_portal/', portal_views.portal_farmer, name='farmer-portal'),
    path('student_portal/', portal_views.portal_student, name='student-portal'),
    #vet forms
    path('clinical_approach/',portal_views.clinical_approach,name='clinical-approach'),
    path('sick_approach', portal_views.sick_approach, name='sick-approach'),
    path('dead_approach', portal_views.dead_approach, name='dead-approach'),
    path('surgical_approach',portal_views.surgical_approach, name='surgical-approach'),
    path('deworming',portal_views.deworming,name='deworming'),
    path('vaccination',portal_views.vaccination,name='vaccination'),
    path('breeding_record/',portal_views.breeding_record,name='breeding_record'),
    path('artificial_insemination', portal_views.artificial_insemination, name='artificial-insemination'),
    path('pregnancy_diagnosis',portal_views.pregnancy_diagnosis,name='pregnancy_diagnosis'),
    path('calf_registration', portal_views.calf_registration, name='calf-registration'),
    path('livestock_inventory', portal_views.livestock_inventory, name='livestock-inventory'),
    path('consultation',portal_views.consultation,name='consultation'),
    #Farmer fetching forms pdf
    path('sickformpdf/', login_required(portal_views.Sick_Form_Pdf.as_view()), name='sickformpdf'),
    path('deadformpdf/', login_required(portal_views.Dead_Form_Pdf.as_view()), name='deadformpdf'),
    path('surgicalformpdf/', login_required(portal_views.Surgical_Form_Pdf.as_view()), name='surgicalformpdf'),
    path('dewormingformpdf/', login_required(portal_views.Deworming_Form_Pdf.as_view()), name='dewormingformpdf'),
    path('artificialformpdf/', login_required(portal_views.Artificial_Insemination_Form_Pdf.as_view()), name='artificialformpdf'),
    path('vaccinationformpdf/', login_required(portal_views.Vaccination_Form_Pdf.as_view()), name='vaccinationformpdf'),
    path('deadformpdf/', login_required(portal_views.Dead_Form_Pdf.as_view()), name='deadformpdf'),
    path('surgicalformpdf/', login_required(portal_views.Surgical_Form_Pdf.as_view()), name='surgicalformpdf'),
    path('dewormingformpdf/', login_required(portal_views.Deworming_Form_Pdf.as_view()), name='dewormingformpdf'),
    path('artificialformpdf/', login_required(portal_views.Artificial_Insemination_Form_Pdf.as_view()), name='artificialformpdf'),
    path('vaccinationpdf/', login_required(portal_views.Vaccination_Form_Pdf.as_view()), name='vaccinationformpdf'),
    path('consultationformpdf/', login_required(portal_views.Farm_Consultation_Form_Pdf.as_view()), name='consultationformpdf'),
    path('pregnancyformpdf/', login_required(portal_views.Pregnancy_Diagnosis_Form_Pdf.as_view()), name='pregnancyformpdf'),
    path('calfregformpdf/', login_required(portal_views.Calf_Registration_Form_Pdf.as_view()), name='calfregformpdf'),
    path('inventorypdf/', login_required(portal_views.Livestock_Form_Pdf.as_view()), name='inventoryformpdf'),
    path('gallerypdf/', portal_views.display_images, name='display-images')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vetWeb/soin/vet/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('ourshop/', views.ourshop, name='Ourshop'),
    path('blog/', views.blog, name='blog'),
    path('contact/', views.contact, name='contact'),  
    path('team/', views.team, name='team'),
    path('events/', views.events, name='events'),
]

vetWeb/soin/portals/models.py
from django.db import models
from user.models import Farm

SPECIES_CHOICES = (
    ('0', 'cattle'),
    ('1', 'sheep'),
	('2', 'goat'),
	('3', 'donkey'),
	('4', 'dog'),
	('5', 'horse'),
	('6', 'poultry'),
	('7','others')
)

DISEASE_CHOICES = (
	('A','acute'),
	('S','sub_acute')

)

DIAGNOSIS_CHOICES = (
	('C','clinical_signs'),
	('L','laboratory')
)

PROGNOSIS_CHOICES=(
	('G','good'),
	('F','fair'),
	('P','poor')
)


YES_NO_CHOICES = (
	('Y','yes'),
	('N','no')
)


OPERATION_CHOICES=(
	('C','c_section'),
 	('I','interstinal_torsion'),
 	('T','tumor_extraction'),
 	('C','canine_spaying'),
 	('H','hernia'),
 	('W','Warts_extraction'),
 	('C','castration'),
 	('S','skin_injuries'),
 	('F','fructure'),
	('R','rumenatomy'),
 	('O','other'),
)

VACCINATION_CHOICES=(
	('M','Mass_vaccination'),
 	('R','Ring_vaccination'),
 	('I','Individual')
)

SEX_CHOICES = (
 	('M','male'),
 	('F','female')
 )


NATURE_CHOICES=(
 	('A','Alive'),
 	('D','Dead')
 )

FARM_MANAGER = (
	('V', 'Veterinary Officer'),
	('L', 'Livestock Officer'),
	('N', 'None')
)

COW_CATEGORY=(
	('A','Adult'),
	('H','Heifer')
)


STATUS_CHOICES=(
 	('H','Healthy'),
 	('D','Deformed')
 )

BREECHING_LEVEL=(
 	('F','First'),
 	('S','Second'),
 	('T','Third'),
 	('P','Pedegree')
)

RESULT_CHOICES=(
 	('P','positive'),
 	('N','Negative')
)




class Vet_Forms(models.Model):
	vet_username = models.CharField(max_length=20)
	is_sick_approach_form = models.BooleanField(default=False)
	is_dead_approach_form= models.BooleanField(default=False)
	is_surgical_approach_form = models.BooleanField(default=False)
	is_deworming_form = models.BooleanField(default=False)
	is_vaccination_form = models.BooleanField(default=False)
	is_artificial_insemination_form = models.BooleanField(default=False)
	is_calf_registration_form = models.BooleanField(default=False)
	is_livestock_inventory_form = models.BooleanField(default=False)
	is_farm_consultation = models.BooleanField(default=False)
	is_pregnancy_diagnosis_form = models.BooleanField(default=False)
	report_created_on = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ['-report_created_on']

	def __str__(self):
		return self.vet_username	


class Sick_Approach_Form(models.Model):
	vet_form = models.OneToOneField(Vet_Forms, on_delete=models.CASCADE, primary_key=True)
	farmer_username = models.CharField(max_length=12, verbose_name='Farmer Username')
	species_affected = models.CharField(max_length=20, choices=SPECIES_CHOICES, default='0', verbose_name='animal species affected',null=True, blank=True)
	num_of_species_affected = models.PositiveIntegerField(verbose_name='number of species affected' ,null=True, blank=True)
	id_animal = models.CharField(max_length=100, verbose_name='name of the animal/identification number', null=True, blank=True)
	disease_nature = models.CharField(max_length=20, choices=DISEASE_CHOICES, default='0', verbose_name='nature of the disease' ,null=True, blank=True)
	clinical_signs = models.CharField(max_length=100)
	disease_diagnosis = models.CharField(max_length=20, choices=DIAGNOSIS_CHOICES, default='0' ,null=True, blank=True)
	differential_diagnosis = models.CharField(max_length=100, null=True, blank=True)
	final_diagnosis = models.CharField(max_length=100 ,null=True, blank=True)
	sickness_duration = models.CharField(max_length=100, verbose_name='duration of the sickness' ,null=True, blank=True)
	sickness_history = models.CharField(max_length=300, null=True, blank=True)
	drug_of_choice = models.CharField(max_length=100, null=True, blank=True)
	treatment_duration = models.CharField(max_length=100 ,null=True, blank=True) 
	start_dose_date = models.DateField()
	prognosis = models.CharField(max_length=20, choices=PROGNOSIS_CHOICES, default='G' ,null=True, blank=True)
	harmony_with_clinic_signs_and_lab = models.CharField(max_length=5, choices=YES_NO_CHOICES, default='Y',verbose_name='were the pathological signs in harmony with the clinical signs and laboratory reports?' ,null=True, blank=True)
	cause_of_death_if_in_no_harmony = models.CharField(max_length=100, null=True, blank=True,verbose_name='If no, what could be the cause of the death')
	disease_one_of_the_zoonotic = models.CharField(max_length=5, choices=YES_NO_CHOICES, default='0', verbose_name='is the disease one of the zoonotic?' ,null=True, blank=True)
	advice_given_if_zoonotic = models.CharField(max_length=100, null=True, blank=True, verbose_name='if yes, what advice did you give the owner and people who handled the carcass')
	relapse = models.CharField(max_length=5, choices=YES_NO_CHOICES, default='0', verbose_name='was there any relapse?')
	cause_if_relapse = models.CharField(max_length=100, null=True, blank=True, verbose_name='if yes, what might be the cause')
	comment = models.CharField(max_length=300,null=True,blank=True,verbose_name='comment')
	
	def __str__(self):
		return f'Sick Form for {self.farmer_username}'
	

class Death_Approach_Form(models.Model):
	vet_form = models.OneToOneField(Vet_Forms, on_delete=models.CASCADE, primary_key=True)
	farmer_username = models.CharField(max_length=12,verbose_name='Farmer Username')
	name_of_the_animal = models.CharField(max_length=30,null=True,blank=True,verbose_name='Name or identification number')
	sex_of_the_animal = models.CharField(max_length=20,choices=SEX_CHOICES,default='',verbose_name='Sex of the animal' ,null=True, blank=True)
	num_of_species_dead = models.IntegerField(default=1,null=True, blank=True,verbose_name='Number of animals dead')
	case_history = models.CharField(max_length=100, default='' ,null=True, blank=True)
	mortality_rate = models.CharField(max_length=100, default='' ,null=True, blank=True)
	death_date = models.DateField(verbose_name='Date the animal died' ,null=True, blank=True)
	death_time = models.TimeField(verbose_name='At what time the animal the animals died' ,null=True, blank=True)
	signs_of_cadever_on_the_ground = models.CharField(max_length=200,verbose_name='What are the signs of signs of the cadever on the ground' ,null=True, blank=True)
	carcass_opened_for_the_pm = models.CharField(max_length=5, choices=YES_NO_CHOICES,default='Y',verbose_name='Did you open up the carcass fo PM?' ,null=True, blank=True)
	if_yes_pathological_signs = models.CharField(max_length=100, null=True, blank=True,verbose_name='If yes,what were the signs of the pathological conditions?')
	if_no_reason = models.CharField(max_length=100, null=True, blank=True,verbose_name='If no,what could have been the reason?')
	sample_sent_lab = models.CharField(max_length=5, choices=YES_NO_CHOICES, default='Y',null=True,verbose_name='Did you send any sample to the laboratory?')
	if_yes_lab_report = models.CharField(max_length=100, null=True, blank=True,verbose_name='if yes,what was the laboratory report?')
	death_cause_notifiable = models.CharField(max_length=5, choices=YES_NO_CHOICES, default='Y',verbose_name='Is the cause of dead notifiable?' ,null=True, blank=True)
	if_yes_message_to_relevant_body = models.CharField(max_length=100, null=True, blank=True,verbose_name='If yes,send message to the relevant body.')
	intervention_regards_to_death = models.CharField(max_length=100, null=True, blank=True,verbose_name='What were the necessary intervention in regard to the cause of the dead')
	comment = models.CharField(max_length=300,null=True,blank=True,verbose_name='comment')

	def __str__(self):
		return f'Name of form: Death Approach Form'


class Surgical_Approach_Form(models.Model):
	vet_form = models.OneToOneField(Vet_Forms, on_delete=models.CASCADE, primary_key=True)
	farmer_username = models.CharField(max_length=12,verbose_name='Farmer Username', default='')
	species_operated_on = models.CharField(max_length=20, choices=SPECIES_CHOICES, default='0',verbose_name='Animal species affected' ,null=True, blank=True)
	if_other_specify = models.CharField(max_length=100, null=True, blank=True,verbose_name='If,other specify.')
	sex_of_the_animal = models.CharField(max_length=20,choices=SEX_CHOICES, default='', verbose_name='Sex of the animal' ,null=True, blank=True)
	name_of_the_animal = models.CharField(max_length=30,null=True,blank=True,verbose_name='Name or identification number')
	operation_nature= models.CharField(max_length=20, choices=OPERATION_CHOICES,default='C', verbose_name='Nature of operation' ,null=True, blank=True)
	if_other_specify = models.CharField(max_length=100, null=True, blank=True)
	operation_date = models.DateField(verbose_name='Date of Operation',null=True, blank=True)
	post_operation_management = models.CharField(max_length=100, default='',null=True, blank=True, verbose_name='Post operation management')
	prognosis = models.CharField(max_length=100, default='',null=True, blank=True,verbose_name='Prognosis')
	comment = models.CharField(max_length=100, null=True, blank=True)

	def __str__(self):
		return f'Name of form: Surgical Approach Form'


class Deworming_Form(models.Model):
	vet_form = models.OneToOneField(Vet_Forms, on_delete=models.CASCADE, primary_key=True)
	farmer_username = models.CharField(max_length=12,verbose_name='Farmer Username')
	species_targeted = models.CharField(max_length=20, choices=SPECIES_CHOICES, default='0',verbose_name='Species targetted' ,null=True, blank=True)
	number_of_adults = models.PositiveIntegerField(default=0,null=True, blank=True,verbose_name='Number of adults')
	number_of_young_ones = models.PositiveIntegerField(default=0,null=True, blank=True,verbose_name='Number of young ones')
	body_condition_of_the_animal = models.CharField(max_length=20, choices=PROGNOSIS_CHOICES, default='G',verbose_name='Body condition of the animal(s)' ,null=True, blank=True)
	date_of_deworming = models.DateField()
	drug_choices = models.CharField(max_length=100, default='',verbose_name='Drug of choice' ,null=True, blank=True)
	target_parasites = models.CharField(max_length=100, null=True, blank=True,verbose_name='Target parasite')
	withdrawal_period = models.CharField(max_length=100 ,null=True, blank=True)

vetWeb/soin/vet/models.py
from django.db import models

# Create your models here.

vetWeb/soin/vet/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'vet/index.html')


def about(request):
    return render(request, 'vet/about.html')    

def services(request):
    return render(request, 'vet/services.html')

def ourshop(request):
    return render(request, 'vet/Ourshop.html') 

def blog(request):
    return render(request, 'vet/blog.html')   

def contact(request):
    return render(request, 'vet/contact.html')  

def team(request):
    return render(request, 'vet/team.html')   

def events(request):
    return render(request, 'vet/events.html')   

vetWeb/soin/portals/templates/portals/artificial_form_pdf.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Vaccination Form </title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }

        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }

        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
        }

        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }

        .table tbody + tbody {
            border-top: 2px solid #000;
        }

        .table .table {
            background-color: #fff;
        }

        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }

        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }

    </style>
</head>
<body>

{% for form in forms %}
<div class="container">
    <div class="card">
        <h2 class="text-center"> Vaccination pdf  </h2>
        <div class="card-header">      
            <h3>DATE : {{form.vet_form.report_created_on}}</h3>
        </div>

        <div class="list-group">
            <p>Vet Officer Name: {{form.vet_form.vet_username}} </p>
            <p>Farmer Name {{ request.user }}</p>     
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Field</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Name of the cow or identification number of the cow</td>
                    <td>{{ form.Name_of_the_cow  }}</td>
                <tr>
                <tr>
                    <td>Time of heat sign</td>
                    <td>{{ form.time_of_heat_sign }}</td>
                </tr>
                <tr>
                    <td>Time of insemination</td>
                    <td>{{ form.time_of_inseminatio }}</td>
                </tr>
                <tr>
                    <td>Date of insemination</td>
                    <td>{{ form.date_of_insemination }}</td>
                </tr>
                <tr>
                    <td>Nature of breeding</td>
                    <td>{{ form.nature_of_the_breeding }}</td>
                </tr>
                <tr>
                    <td>Sire`s name</td>
                    <td>{{ form.sire_name }}</td>
                </tr>
                <tr>
                    <td>Sire origin</td>
                    <td>{{ form.sire_origin }}</td>
                </tr>
                <tr>
                    <td>Bull code</td>
                    <td>{{ form.bull_code }}</td>
                </tr>
                <tr>
                    <td>Sex of the calf born</td>
                    <td>{{ form.get_sex_of_the_calf_born_display }}</td>
                </tr>
                <tr>
                    <td>Date of birth</td>
                    <td>{{ form.date_of_birth }}</td>
                </tr>
                <tr>
                    <td>Nature of birth</td>
                    <td>{{ form.get_nature_of_birth_display }}</td>
                </tr>
                <tr>
                    <td>Number of repeat</td>
                    <td>{{ form.number_of_repeat }}</td>
                </tr>
                <tr>
                    <td>Abortion rate</td>
                    <td>{{ form.abortion_rate }}</td>
                </tr>
                <tr>
                    <td>reason for abortion</td>
                    <td>{{ form.reason_for_the_cause_of_abortion }}</td>
                </tr>   
                <tr>
                    <td>Breed used</td>
                    <td>{{ form.breed_used }}</td>
                </tr>
                <tr>
                    <td>Source of the semen</td>
                    <td>{{ form.source_of_semen }}</td>
                </tr>
                <tr>
                    <td>Date of repeat check</td>
                    <td>{{ form.date_of_repeat_checked }}</td>
                </tr>
                <tr>
                    <td>Date of pregnancy</td>
                    <td>{{ form.date_of_pregnancy_diagnosis }}</td>
                </tr>
                <tr>
                    <td>expected date of calving</td>
                    <td>{{ form.expected_date_of_calving }}</td>
                </tr>
                <tr>
                    <td>Comment</td>
                    <td>{{ form.Comment }}</td>
                </tr>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <th>Field</th>
                <th>Value</th>
            </tr>
        </tfoot>
    </table>
    </div>
</div>
{% endfor %}
</body>
</html>

vetWeb/soin/portals/templates/portals/surgical_form_pdf.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Surgical Form </title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }

        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }

        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
        }

        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }

        .table tbody + tbody {
            border-top: 2px solid #000;
        }

        .table .table {
            background-color: #fff;
        }

        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }

        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }

    </style>
</head>
<body>
    {% for form in forms %}
<div class="container">
    <div class="card">
        <h2 class="text-center">Surgical form  </h2>
        <div class="card-header">      
            <h3>DATE : {{form.vet_form.report_created_on}}</h3>
        </div>

        <div class="list-group">
            <p>Vet Officer Name: {{form.vet_form.vet_username}} </p>
            <p>Farmer Name {{ request.user }}</p>     
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Field</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Animal species affected</td>
                    <td>{{ form.species_operated_on }}</td>
                </tr>
                <tr>
                    <td>If,other specify.</td>
                    <td>{{ form.if_other_specify }}</td>
                </tr>
                <tr>
                    <td>Sex of the animal</td>
                    <td>{{ form.get_sex_of_the_animal_display }}</td>
                </tr>
                <tr>
                    <td>Name or identification number</td>
                    <td>{{ form.name_of_the_animal }}</td>
                </tr>
                <tr>
                    <td>Nature of operation</td>
                    <td>{{ form.get_operation_nature_display }}</td>
                </tr>
                <tr>
                    <td>If others, Specify</td>
                    <td>{{ form.if_other_specify }}</td>
                </tr>
                <tr>
                    <td>Date of Operation</td>
                    <td>{{ form.operation_date }}</td>
                </tr>
                <tr>
                    <td>Post operation management</td>
                    <td>{{ form.post_operation_management }}</td>
                </tr>
                <tr>
                    <td>Prognosis</td>
                    <td>{{ form.prognosis }}</td>
                </tr>
                <tr>
                    <td>Comment</td>
                    <td>{{ form.comment }}</td>
                </tr>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <th>Field</th>
                <th>Value</th>
            </tr>
        </tfoot>
    </table>
    </div>
</div>
   {% endfor %}
</body>
</html>

vetWeb/soin/portals/templates/portals/vaccination_pdf_form.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Vaccination Form </title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }

        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }

        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
        }

        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }

        .table tbody + tbody {
            border-top: 2px solid #000;
        }

        .table .table {
            background-color: #fff;
        }

        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }

        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }

    </style>
</head>
<body>

{% for form in forms %}
<div class="container">
    <div class="card">
        <h2 class="text-center"> Vaccination pdf  </h2>
        <div class="card-header">      
            <h3>DATE : {{form.vet_form.report_created_on}}</h3>
        </div>

        <div class="list-group">
            <p>Vet Officer Name: {{form.vet_form.vet_username}} </p>
            <p>Farmer Name {{ request.user }}</p>     
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Field</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Animal species targetted</td>
                    <td>{{ form.species_targeted }}</td>
                <tr>
                    <td>If other specify</td>
                    <td>{{ form.if_other_specify  }}</td>
                </tr>   
                <tr>
                    <td>Number of animals vaccinated.</td>
                    <td>{{ form.number_of_animals_vaccinated }}</td>
                </tr> 
                <tr>
                    <td>Age of animal</td>
                    <td>{{ form.age_of_animal }}</td>
                </tr>
                <tr>
                    <td>Sex of the animal</td>
                    <td>{{ form.get_sex_of_the_animal_display }}</td>
                </tr>
                <tr>
                    <td>Breed of the animal</td>
                    <td>{{ form.animal_breed }}</td>
                </tr>
                <tr>
                    <td>Colour of the animal</td>
                    <td>{{ form.animal_colour }}</td>
                </tr>
                <tr>
                    <td>other description</td>
                    <td>{{ form.other_description }}</td>
                </tr>
                <tr>
                    <td>The disease target</td>
                    <td>{{ form.targetted_disease }}</td>
                </tr>
                <tr>
                    <td>Vaccine used</td>
                    <td>{{ form.vaccines_used }}</td>
                </tr>
                <tr>
                    <td>Date of vaccination</td>
                    <td>{{ form.date_of_vaccination }}</td>
                </tr>
                <tr>
                    <td>Next date of vaccination</td>
                    <td>{{ form.next_date_of_vaccination  }}</td>
                </tr>
                <tr>
                    <td>Name of the crush</td>
                    <td>{{ form.name_of_the_crush }}</td>
                </tr>
                <tr>
                    <td>Nature of the vaccination program</td>
                    <td>{{ form.get_nature_of_the_vacination_program_display }}</td>
                </tr>
                <tr>
                    <td>Comment</td>
                    <td>{{ form.Comment }}</td>
                </tr>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <th>Field</th>
                <th>Value</th>
            </tr>
        </tfoot>
    </table>
</div>
{% endfor %}
</div>

</body>
</html>